### ISSUE TITLE
[Important] About the project status and owner

### ISSUE THREAD

**Issue by greenmg2003** [greenmg2003/osu-mg-reload#25]
Hello there! Alpha Mg here, this is my primary main account of this project. As of now, we still have some works to do, that is to upload files, mentioned at #2. After GitHub finished reviewing, I'll re-own the project with the account @greenmg2003 and continue the work! My alt, @alphamg2003, will be granted with review ability, so that we can update the pull request system and create a better experience. 

Thank you so much for the support, if you are the one who uses my skin before and supported me!

**Comment by alphamg2003** [comment]
Good news: GitHub lifted the flag!!
